apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipts-tracker
  labels:
    app: receipts-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipts-tracker
  template:
    metadata:
      labels:
        app: receipts-tracker
    spec:
      containers:
        - name: receipts-tracker
          image: receipts-tracker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PORT
            - name: DB_URL
              value: "postgresql://$(PG_USER):$(PG_PASSWORD)@receipts-db:$(DB_PORT)/$(PG_DB)"
            - name: TESSDATA_PREFIX
              value: "/usr/share/tessdata"
          livenessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
